import { Link } from 'react-router-dom';

export default function Home() {
  const highlights = [
    { label: 'Total Clarity', value: '100%', note: 'single dashboard visibility' },
    { label: 'Planning Horizon', value: '12m', note: 'monthly budget foresight' },
    { label: 'Action Speed', value: '< 60s', note: 'to log a new transaction' },
    { label: 'Insight Type', value: 'Rule Based', note: 'no black-box AI guesses' }
  ];

  const featureCards = [
    {
      title: 'Unified Money Feed',
      text: 'Income and expense streams sit in one place with categories, search, and quick edits so records stay clean and useful.'
    },
    {
      title: 'Budget Guardrails',
      text: 'Monthly category budgets help you stay intentional. Spot overspending early instead of reacting late.'
    },
    {
      title: 'Visual Breakdown',
      text: 'Pie, bar, and trend charts make patterns obvious. You see where cash is leaking and where savings are improving.'
    },
    {
      title: 'Practical Insights',
      text: 'Smart rules evaluate your own numbers and generate focused suggestions you can act on today.'
    }
  ];

  const flowSteps = [
    {
      step: 'Step 1',
      title: 'Capture',
      text: 'Record income and expense entries with date, category, and notes.'
    },
    {
      step: 'Step 2',
      title: 'Plan',
      text: 'Set monthly budget targets by category to create clear spending boundaries.'
    },
    {
      step: 'Step 3',
      title: 'Analyze',
      text: 'Open analytics and reports to compare monthly behavior and category trends.'
    },
    {
      step: 'Step 4',
      title: 'Improve',
      text: 'Use rule-based insights to adjust habits and grow your monthly savings rate.'
    }
  ];

  const faqs = [
    {
      q: 'Is this app suitable for students or first-time budgeters?',
      a: 'Yes. The interface is intentionally straightforward, with clear labels and practical metrics that are easy to learn.'
    },
    {
      q: 'Can I review past spending behavior quickly?',
      a: 'Absolutely. Transaction history supports filtering and sorting, and reports provide monthly summaries and category totals.'
    },
    {
      q: 'Does it export data for sharing or records?',
      a: 'Yes. You can download CSV reports for both income and expense records directly from the reports page.'
    },
    {
      q: 'Are smart insights generated by AI?',
      a: 'No. Insights are deterministic, rule-based checks against your own real transaction and budget numbers.'
    }
  ];

  return (
    <div className="page home-page">
      <section className="home-hero">
        <div className="home-hero-copy reveal-up">
          <p className="home-kicker">Personal Finance, Rebuilt for Clarity</p>
          <h1>BudgetWise</h1>
          <p className="hero-subtitle">Smart Expense Tracker with Budget Analytics</p>
          <p>
            BudgetWise helps you build calm, data-driven money habits. Track cash flow,
            set realistic monthly limits, and understand spending patterns with clean
            analytics that turn raw transactions into better decisions.
          </p>
          <div className="hero-actions">
            <Link to="/register" className="btn-primary">Start Free</Link>
            <Link to="/login" className="btn-secondary">Sign In</Link>
          </div>
          <div className="hero-meta">
            <span>Income + Expense Tracking</span>
            <span>Budget Alerts</span>
            <span>CSV Reports</span>
          </div>
        </div>

        <div className="home-hero-panel reveal-up delay-1">
          <h3>This Month at a Glance</h3>
          <div className="hero-panel-grid">
            {highlights.map((item) => (
              <article key={item.label} className="hero-stat-box">
                <p>{item.label}</p>
                <h4>{item.value}</h4>
                <small>{item.note}</small>
              </article>
            ))}
          </div>
        </div>
      </section>

      <section className="home-section reveal-up delay-1">
        <div className="home-section-head">
          <p className="home-kicker">Why It Works</p>
          <h2>Four Core Capabilities for Better Monthly Control</h2>
        </div>
        <div className="features-grid">
          {featureCards.map((feature) => (
            <article className="feature-card" key={feature.title}>
              <h3>{feature.title}</h3>
              <p>{feature.text}</p>
            </article>
          ))}
        </div>
      </section>

      <section className="home-section home-split reveal-up">
        <div>
          <p className="home-kicker">What You Can See</p>
          <h2>Understand Your Money Story, Not Just Numbers</h2>
          <p>
            Monthly reports combine income, expenses, savings, and category-level totals.
            Instead of jumping between multiple tools, you get one practical view that helps
            you answer real questions: where did I overspend, what improved, and what should
            I adjust this month?
          </p>
          <ul className="home-bullets">
            <li>Searchable transaction history with filters and sorting.</li>
            <li>Category budgets with quick variance checks.</li>
            <li>Trend charts that reveal recurring spending spikes.</li>
            <li>Profile and account controls in one secure place.</li>
          </ul>
        </div>

        <aside className="home-note-card">
          <h3>Designed for Action</h3>
          <p>
            BudgetWise does not overwhelm you with noise. Every screen is tuned for
            quick decisions: add, compare, adjust, and move forward.
          </p>
          <div className="note-metrics">
            <div>
              <strong>Monthly Summary</strong>
              <span>Income, Expense, Savings</span>
            </div>
            <div>
              <strong>Insight Feed</strong>
              <span>Overspend and savings signals</span>
            </div>
            <div>
              <strong>Export Ready</strong>
              <span>CSV downloads for records</span>
            </div>
          </div>
        </aside>
      </section>

      <section className="home-section reveal-up delay-1">
        <div className="home-section-head">
          <p className="home-kicker">How It Flows</p>
          <h2>From Daily Entries to Clear Monthly Decisions</h2>
        </div>
        <div className="process-grid">
          {flowSteps.map((step) => (
            <article className="process-card" key={step.step}>
              <p>{step.step}</p>
              <h3>{step.title}</h3>
              <span>{step.text}</span>
            </article>
          ))}
        </div>
      </section>

      <section className="home-section home-band reveal-up">
        <div className="home-section-head">
          <p className="home-kicker">Built for Real Life</p>
          <h2>Simple Enough for Daily Use, Powerful Enough for Planning</h2>
        </div>
        <p>
          Whether you are tracking your first monthly budget or managing multiple spending
          categories, BudgetWise gives you enough depth without complexity overload.
          Keep records tidy, monitor budget health, and improve over time with data you trust.
        </p>
      </section>

      <section className="home-section reveal-up delay-1">
        <div className="home-section-head">
          <p className="home-kicker">FAQ</p>
          <h2>Common Questions</h2>
        </div>
        <div className="faq-grid">
          {faqs.map((item) => (
            <article key={item.q} className="faq-card">
              <h3>{item.q}</h3>
              <p>{item.a}</p>
            </article>
          ))}
        </div>
      </section>

      <section className="home-section home-cta reveal-up">
        <div>
          <h2>Start Building a Better Money Routine Today</h2>
          <p>
            Create your account, log your first entries, and let BudgetWise guide your
            next month with clearer priorities and stronger spending discipline.
          </p>
        </div>
        <div className="hero-actions">
          <Link to="/register" className="btn-primary">Create Account</Link>
          <Link to="/login" className="btn-secondary">I Already Have an Account</Link>
        </div>
      </section>
    </div>
  );
}
